export const Cities = [
    { value: 'Tel Aviv', label: 'Tel Aviv' },                 
    { value: 'Jerusalem', label: 'Jerusalem' },               
    { value: 'Haifa', label: 'Haifa' },                       
    { value: 'Rishon LeZion', label: 'Rishon LeZion' },       
    { value: 'Petah Tikva', label: 'Petah Tikva' },           
    { value: 'Ashdod', label: 'Ashdod' },                  
    { value: 'Netanya', label: 'Netanya' },                   
    { value: 'Beer Sheva', label: 'Beer Sheva' },             
    { value: 'Bnei Brak', label: 'Bnei Brak' },              
    { value: 'Holon', label: 'Holon' },                      
    { value: 'Bat Yam', label: 'Bat Yam' },                   
    { value: 'Ramat Gan', label: 'Ramat Gan' },              
    { value: 'Ashkelon', label: 'Ashkelon' },                
    { value: 'Herzliya', label: 'Herzliya' },                 
    { value: 'Kfar Saba', label: 'Kfar Saba' },               
    { value: "Ra'nana", label: "Ra'anana" },               
    { value: "Modi'in", label: "Modi'in" },                
    { value: 'Nahariya', label: 'Nahariya' },                 
    { value: 'Beit Shemesh', label: 'Beit Shemesh' },         
    { value: 'Lod', label: 'Lod' },                           
    { value: 'Netivot', label: 'Netivot' },                   
    { value: 'Hod HaSharon', label: 'Hod HaSharon' },         
    { value: 'Ashdod Yam', label: 'Ashdod Yam' },             
    { value: 'Kiryat Gat', label: 'Kiryat Gat' },            
    { value: 'Acre', label: 'Acre' },                        
    { value: 'Safed', label: 'Safed' },                     
    { value: 'Eilat', label: 'Eilat' },                     
    { value: 'Dimona', label: 'Dimona' },                    
    { value: 'Arad', label: 'Arad' },                         
    { value: 'Migdal HaEmek', label: 'Migdal HaEmek' },       
    { value: 'Nesher', label: 'Nesher' },                     
    { value: 'Yavne', label: 'Yavne' },                       
    { value: 'Or Yehuda', label: 'Or Yehuda'},
    { value: 'Sderot', label: 'Sderot' },                     
    { value: 'Tiberias', label: 'Tiberias' },                
    { value: 'Kiryat Shmona', label: 'Kiryat Shmona' },       
    { value: 'Tirat Carmel', label: 'Tirat Carmel' },         
    { value: 'Rosh HaAyin', label: 'Rosh HaAyin' },          
    { value: 'Ramat HaSharon', label: 'Ramat HaSharon' },     
    { value: 'Qalansawe', label: 'Qalansawe' },               
    { value: 'Kafr Qasim', label: 'Kafr Qasim' },            
    { value: 'Tamra', label: 'Tamra' },                       
    { value: 'Kiryat Yam', label: 'Kiryat Yam' },            
    { value: 'Givatayim', label: 'Givatayim' },               
    { value: 'Eilabun', label: 'Eilabun' },                   
    { value: 'Kafr Manda', label: 'Kafr Manda' },            
    { value: 'Kafr Kanna', label: 'Kafr Kanna' }, 
    { value: 'Sakhnin', label: 'Sakhnin' },                 
    { value: 'Yehud', label: 'Yehud' },                       
    { value: 'Umm al-Fahm', label: 'Umm al-Fahm' },           
    { value: 'Afula', label: 'Afula' },                       
    { value: 'Netivot', label: 'Netivot' },                   
    { value: 'Kiryat Motzkin', label: 'Kiryat Motzkin' },     
    { value: 'Ofakim', label: 'Ofakim' },                     
    { value: 'Karmiel', label: 'Karmiel' },                   
    { value: 'Kiryat Gat', label: 'Kiryat Gat' },            
    { value: 'Nof HaGalil', label: 'Nof HaGalil' },         
    { value: 'Kiryat Malakhi', label: 'Kiryat Malakhi' },    
    { value: 'Tayibe', label: 'Tayibe' },                    
    { value: 'Arad', label: 'Arad' },                        
    { value: 'Eilat', label: 'Eilat' },                      
    { value: 'Kiryat Bialik', label: 'Kiryat Bialik' },       
    { value: 'Migdal HaEmek', label: 'Migdal HaEmek' },       
    { value: 'Yavne', label: 'Yavne' },                     
    { value: 'Sderot', label: 'Sderot' },                     
    { value: 'Modiin Illit', label: 'Modiin Illit' },        
    { value: 'Qiryat Yam', label: 'Qiryat Yam' },           
    { value: 'Kafr Yasif', label: 'Kafr Yasif' },             
    { value: 'Acre', label: 'Acre' },                        
    { value: 'Kiryat Ono', label: 'Kiryat Ono' },             
    { value: 'Tira', label: 'Tira' },                         
    { value: 'Tel Mond', label: 'Tel Mond' },              
    { value: 'Kiryat Shalom', label: 'Kiryat Shalom' },       
    { value: 'Ganei Tikva', label: 'Ganei Tikva' },          
    { value: 'Rahat', label: 'Rahat' },                       
    { value: 'Kiryat Ekron', label: 'Kiryat Ekron' },        
    { value: 'Or Akiva', label: 'Or Akiva' },                
    { value: 'Kfar Yona', label: 'Kfar Yona' }, 
    { value: 'Beit Jann', label: 'Beit Jann' },
    {value: 'Kiryat Tivon', label: 'Kiryat Tivon' },
    { value: 'Yokneam', label: 'Yokneam' }, 
    { value: 'Kafr Kanna', label: 'Kafr Kanna' }, 
];
