export const Cities = [
    { value: 1, label: 'Tel Aviv' },
    { value: 2, label: 'Haifa' },
    { value: 3, label: 'Jerusalem' },
    { value: 4, label: 'Rishon LeZion' },
    { value: 5, label: 'Petah Tikva' },
    { value: 6, label: 'Ashdod' },
    { value: 7, label: 'Netanya' },
    { value: 8, label: 'Beer Sheva' },
    { value: 9, label: 'Bnei Brak' },
    { value: 10, label: 'Holon' },
    { value: 11, label: 'Bat Yam' },
    { value: 12, label: 'Ramat Gan' },
    { value: 13, label: 'Ashkelon' },
    { value: 14, label: 'Herzliya' },
    { value: 15, label: 'Kfar Saba' },
    { value: 16, label: "Ra'anana" },
    { value: 17, label: "Modi'in" },
    { value: 18, label: 'Nahariya' },
    { value: 19, label: 'Beit Shemesh' },
    { value: 20, label: 'Lod' },
    { value: 21, label: 'Netivot' },
    { value: 22, label: 'Hod HaSharon' },
    { value: 23, label: 'Ashdod Yam' },
    { value: 24, label: 'Kiryat Gat' },
    { value: 25, label: 'Acre' },
    { value: 26, label: 'Safed' },
    { value: 27, label: 'Eilat' },
    { value: 28, label: 'Dimona' },
    { value: 29, label: 'Arad' },
    { value: 30, label: 'Migdal HaEmek' },
    { value: 31, label: 'Nesher' },
    { value: 32, label: 'Yavne' },
    { value: 33, label: 'Or Yehuda' },
    { value: 34, label: 'Sderot' },
    { value: 35, label: 'Tiberias' },
    { value: 36, label: 'Kiryat Shmona' },
    { value: 37, label: 'Tirat Carmel' },
    { value: 38, label: 'Rosh HaAyin' },
    { value: 39, label: 'Ramat HaSharon' },
    { value: 40, label: 'Qalansawe' },
    { value: 41, label: 'Kafr Qasim' },
    { value: 42, label: 'Tamra' },
    { value: 43, label: 'Kiryat Yam' },
    { value: 44, label: 'Givatayim' },
    { value: 45, label: 'Eilabun' },
    { value: 46, label: 'Kafr Manda' },
    { value: 47, label: 'Kafr Kanna' },
    { value: 48, label: 'Sakhnin' },
    { value: 49, label: 'Yehud' },
    { value: 50, label: 'Umm al-Fahm' },
    { value: 51, label: 'Afula' },
    { value: 52, label: 'Netivot' },
    { value: 53, label: 'Kiryat Motzkin' },
    { value: 54, label: 'Ofakim' },
    { value: 55, label: 'Karmiel' },
    { value: 56, label: 'Kiryat Gat' },
    { value: 57, label: 'Nof HaGalil' },
    { value: 58, label: 'Kiryat Malakhi' },
    { value: 59, label: 'Tayibe' },
    { value: 60, label: 'Arad' },
    { value: 61, label: 'Eilat' },
    { value: 62, label: 'Kiryat Bialik' },
    { value: 63, label: 'Migdal HaEmek' },
    { value: 64, label: 'Yavne' },
    { value: 65, label: 'Sderot' },
    { value: 66, label: 'Modiin Illit' },
    { value: 67, label: 'Qiryat Yam' },
    { value: 68, label: 'Kafr Yasif' },
    { value: 69, label: 'Acre' },
    { value: 70, label: 'Kiryat Ono' },
    { value: 71, label: 'Tira' },
    { value: 72, label: 'Tel Mond' },
    { value: 73, label: 'Kiryat Shalom' },
    { value: 74, label: 'Ganei Tikva' },
    { value: 75, label: 'Rahat' },
    { value: 76, label: 'Kiryat Ekron' },
    { value: 77, label: 'Or Akiva' },
    { value: 78, label: 'Kfar Yona' },
    { value: 79, label: 'Beit Jann' },
    { value: 80, label: 'Kiryat Tivon' },
    { value: 81, label: 'Yokneam' },
    { value: 82, label: 'Kafr Kanna' },
  ];
  